version: "3.8"
volumes:
  data: {}
services:
    mongodb:
      image: mongo
      container_name: mongodb
      hostname: mongo
      ports:
          - 27017:27017
      volumes:
          - data:/data
      environment:
        - MONGO_INITDB_ROOT_USERNAME=rootuser
        - MONGO_INITDB_ROOT_PASSWORD=rootpass
      networks:
        sneakydrop:
    mongo-express:
      image: mongo-express
      container_name: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
        - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
        - ME_CONFIG_MONGODB_SERVER=mongodb
      networks:
        sneakydrop:
    backend:
      build: ./Backend
      container_name: backend
      hostname: backend
      expose:
        - 8080
      depends_on:
        - mongodb
      ports:
        - 8080:8080
      environment:
        - SERVER_PORT=8080
        - SPRING_PROFILES_ACTIVE=prod
        - SPRING_APPLICATION_NAME=backend
        - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
        - SPRING_DATA_MONGODB_HOST=mongo
        - SPRING_DATA_MONGODB_PORT=27017
        - SPRING_DATA_MONGODB_USERNAME=rootuser
        - SPRING_DATA_MONGODB_PASSWORD=rootpass
        - SPRING_DATA_MONGODB_DATABSE=mongodb
      networks:
        sneakydrop:
    frontend:
      build: ./frontend
      container_name: frontend
      hostname: frontend
      expose: 
        - 3000
      ports:
        - 3000:3000
      depends_on:
        - backend
      environment:
        - CHOKIDAR_USEPOLLING=true 
      links:
        - backend
      networks:
        sneakydrop:
networks:
  sneakydrop: